### ISSUE TITLE
Using Rasbian Pi OS (64bit)

### ISSUE THREAD

**Issue by Hackerman2016** [openMLA/elegoo-mars-4-dlp-controller#3]
In the project, you have used the Rasbian Pi OS Lite. I was wondering if there is any specific reason for that. can I use the Rasbian Pi OS (64bit) instead, and would the same Python script work for that? Also, will the commands for installing Python libraries remain the same? Any help with this would be great. Thanks!

**Comment by NemoAndrea** [comment]
The normal raspberry Pi OS should work fine. It may be that the normal OS already has some of the dependencies installed (which isn't bad). I use the Lite version because I don't need a desktop environment anyway (just accessing the Pi over SSH), so then the Lite version will give better boot times and performance.
